sort: true
formatter: markdown
output:
  file: README.md
  mode: inject
  template: |
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

sections:
  header: {}
  requirements: {}
  providers: {}
  modules: {}
  resources: {}
  inputs: {}
  outputs: {}
