formatter: markdown

output:
  file: README.md
  mode: inject
  template: |
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

sections:
  header: true
  requirements: true
  providers: true
  modules: true
  resources: true
  inputs: true
  outputs: true
